# Site settings
title: Shafeeq & Nadia
email: nikamirulmukmeen@gmail.com
description: We are getting married!
baseurl: "/shafeeqnadia" # the subpath of your site, e.g. /blog
url: "https://satuhearty.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url: https://www.facebook.com/satuhearty
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/satuhearty
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://www.twitter.com/satuhearty

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, webpack, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]